name: arsync_supabase_errors_handler

description: An error handling solution for Supabase services. Provides user-friendly error messages, standardized error handling, and integration with the Arsync Exception Toolkit.
version: 0.0.2
homepage: https://arsyncsolutions.com/
repository: https://github.com/itsatifsiddiqui/arsync_packages


environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  arsync_exception_toolkit: ^0.0.8
  supabase_flutter: ^2.8.4
  supabase: ^2.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For local development, uncomment this
# dependency_overrides:
#   arsync_exception_toolkit:
#     path: ../arsync_exception_toolkit

flutter:
  uses-material-design: true