name: arsync_image_compression
description: Image compression addon for arsync_image_picker
version: 0.0.2
homepage: https://arsyncsolutions.com/
repository: https://github.com/itsatifsiddiqui/arsync_packages

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter
  arsync_image_picker: ^0.0.2
  flutter_image_compress: ^2.4.0
  path: ^1.9.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

topics:
  - image-compression
  - image-processing